var homes_wallpaper_configs = {
	"8bit"				: {
		"name"		: "8bit Meadow Wallpaper",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "eightbit_wall",
		"wall_2"	: "eightbit_wall_2",
		"wall_3"	: "eightbit_wall_3",
		"wall_4"	: "eightbit_wall_4",
		"wall_5"	: "eightbit_wall_5",
		"wall_6"	: "eightbit_wall_6",
		"wall_left"	: "eightbit_wall",
		"wall_right"	: "eightbit_wall",
		"wall_single"	: "eightbit_wall",
		"left"		: "eightbit_left",
		"right"		: "eightbit_left,FLIP",
		"left_open"	: "eightbit_left_open",
		"left_divide"	: "eightbit_left_divide",
		"right_divide"	: "eightbit_left_divide,FLIP",
		"swatch"	: "eightbit_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: true,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"lightbrown_stucco"		: {
		"name"		: "Almond Frost Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "lightbrown_stucco_wall",
		"wall_left"	: "lightbrown_stucco_wall",
		"wall_right"	: "lightbrown_stucco_wall",
		"wall_single"	: "lightbrown_stucco_wall",
		"left"		: "lightbrown_stucco_left",
		"right"		: "lightbrown_stucco_left,FLIP",
		"left_open"	: "lightbrown_stucco_left_open",
		"left_divide"	: "lightbrown_stucco_left_divide",
		"right_divide"	: "lightbrown_stucco_left_divide,FLIP",
		"swatch"	: "lightbrown_stucco_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"brown_molding"			: {
		"name"		: "Almond Frost Stucco with Molding",
		"category"	: "Traditional",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "brownbaseboard_molding_wall",
		"wall_left"	: "brownbaseboard_molding_wall_left",
		"wall_right"	: "brownbaseboard_molding_wall_right",
		"wall_single"	: "brownbaseboard_molding_wall_single",
		"left"		: "brownbaseboard_molding_left",
		"right"		: "brownbaseboard_molding_left,FLIP",
		"left_open"	: "brownbaseboard_molding_left_open",
		"left_divide"	: "brownbaseboard_molding_left_divide",
		"right_divide"	: "brownbaseboard_molding_left_divide,FLIP",
		"swatch"	: "brownbaseboard_molding_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"color_brick"			: {
		"name"		: "Ash Brick Wall",
		"category"	: "Brick",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "color_brick_wall",
		"wall_left"	: "color_brick_wall_left",
		"wall_right"	: "color_brick_wall_right",
		"wall_single"	: "color_brick_wall_single",
		"left"		: "color_brick_left",
		"right"		: "color_brick_right",
		"left_open"	: "color_brick_left_open",
		"left_divide"	: "color_brick_left_divide",
		"right_divide"	: "color_brick_right_divide",
		"swatch"	: "color_brick_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"creamy_stripes"		: {
		"name"		: "Beige Striped Wallpaper",
		"category"	: "Stripes",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "creamy_stripes_wall",
		"wall_left"	: "creamy_stripes_wall",
		"wall_right"	: "creamy_stripes_wall",
		"wall_single"	: "creamy_stripes_wall",
		"left"		: "creamy_stripes_left",
		"right"		: "creamy_stripes_right",
		"left_open"	: "creamy_stripes_left_open",
		"left_divide"	: "creamy_stripes_left_divide",
		"right_divide"	: "creamy_stripes_right_divide",
		"swatch"	: "creamy_stripes_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"blue_stripes"			: {
		"name"		: "Blue Rainbow Wallpaper",
		"category"	: "Stripes",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "blue_stripes_wall",
		"wall_left"	: "blue_stripes_wall",
		"wall_right"	: "blue_stripes_wall",
		"wall_single"	: "blue_stripes_wall",
		"left"		: "blue_stripes_left",
		"right"		: "blue_stripes_right",
		"left_open"	: "blue_stripes_left_open",
		"left_divide"	: "blue_stripes_left_divide",
		"right_divide"	: "blue_stripes_right_divide",
		"swatch"	: "blue_stripes_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"blue_tiles"			: {
		"name"		: "Blue Tiles",
		"category"	: "Tiles",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "blue_tiles_wall",
		"wall_left"	: "blue_tiles_wall",
		"wall_right"	: "blue_tiles_wall",
		"wall_single"	: "blue_tiles_wall",
		"left"		: "blue_tiles_left",
		"right"		: "blue_tiles_left,FLIP",
		"left_open"	: "blue_tiles_left_open",
		"left_divide"	: "blue_tiles_left_divide",
		"right_divide"	: "blue_tiles_left_divide,FLIP",
		"swatch"	: "blue_tiles_swatch",
		"cost_credits"	: 25,
		"is_visible"	: false,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"brown_boghouse"		: {
		"name"		: "Brown Bog Wallpaper",
		"category"	: "Wood",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "brown_boghouse_wall",
		"wall_left"	: "brown_boghouse_wall_left",
		"wall_right"	: "brown_boghouse_wall_left,FLIP",
		"wall_single"	: "brown_boghouse_wall",
		"left"		: "brown_boghouse_left",
		"right"		: "brown_boghouse_left,FLIP",
		"left_open"	: "brown_boghouse_left_open",
		"left_divide"	: "brown_boghouse_left_divide",
		"right_divide"	: "brown_boghouse_left_divide,FLIP",
		"swatch"	: "brown_boghouse_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"brown_stripes"			: {
		"name"		: "Brown Striped Walls",
		"category"	: "Stripes",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "brown_stripes_wall",
		"wall_left"	: "brown_stripes_wall",
		"wall_right"	: "brown_stripes_wall",
		"wall_single"	: "brown_stripes_wall",
		"left"		: "brown_stripes_left",
		"right"		: "brown_stripes_right",
		"left_open"	: "brown_stripes_left_open",
		"left_divide"	: "brown_stripes_left_divide",
		"right_divide"	: "brown_stripes_right_divide",
		"swatch"	: "brown_stripes_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"brownbaseboard_molding"	: {
		"name"		: "Charcoal Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "darkgrey_stucco_wall",
		"wall_left"	: "darkgrey_stucco_wall",
		"wall_right"	: "darkgrey_stucco_wall",
		"wall_single"	: "darkgrey_stucco_wall",
		"left"		: "darkgrey_stucco_left",
		"right"		: "darkgrey_stucco_left,FLIP",
		"left_open"	: "darkgrey_stucco_left_open",
		"left_divide"	: "darkgrey_stucco_left_divide",
		"right_divide"	: "darkgrey_stucco_left_divide,FLIP",
		"swatch"	: "darkgrey_stucco_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"forest_papercut"		: {
		"name"		: "Cutout Mushroom Wallpaper",
		"category"	: "Fun",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "forest_papercut_wall",
		"wall_left"	: "forest_papercut_wall",
		"wall_right"	: "forest_papercut_wall",
		"wall_single"	: "forest_papercut_wall",
		"left"		: "forest_papercut_left",
		"right"		: "forest_papercut_right",
		"left_open"	: "forest_papercut_left_open",
		"left_divide"	: "forest_papercut_left_divide",
		"right_divide"	: "forest_papercut_right_divide",
		"swatch"	: "forest_papercut_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: true,
		"is_default"	: false
	},
	"darkstar_black"		: {
		"name"		: "Dark Starry Sky Wallpaper",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "darkstar_black_wall",
		"wall_2"	: "darkstar_black_wall_2",
		"wall_left"	: "darkstar_black_wall_left",
		"wall_right"	: "darkstar_black_wall_left,FLIP",
		"wall_single"	: "darkstar_black_wall",
		"left"		: "darkstar_black_left",
		"right"		: "darkstar_black_left,FLIP",
		"left_open"	: "darkstar_black_left_open",
		"left_divide"	: "darkstar_black_left_divide",
		"right_divide"	: "darkstar_black_left_divide,FLIP",
		"swatch"	: "darkstar_black_swatch",
		"cost_credits"	: 40,
		"is_visible"	: false,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"tealgreen_stucco"		: {
		"name"		: "Dark Teal Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "tealgreen_stucco_wall",
		"wall_left"	: "tealgreen_stucco_wall",
		"wall_right"	: "tealgreen_stucco_wall",
		"wall_single"	: "tealgreen_stucco_wall",
		"left"		: "tealgreen_stucco_left",
		"right"		: "tealgreen_stucco_left,FLIP",
		"left_open"	: "tealgreen_stucco_left_open",
		"left_divide"	: "tealgreen_stucco_left_divide",
		"right_divide"	: "tealgreen_stucco_left_divide,FLIP",
		"swatch"	: "tealgreen_stucco_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"darktealbaseboard_molding"	: {
		"name"		: "Dark Teal Stucco with Molding",
		"category"	: "Traditional",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "darktealbaseboard_molding_wall",
		"wall_left"	: "darktealbaseboard_molding_wall_left",
		"wall_right"	: "darktealbaseboard_molding_wall_right",
		"wall_single"	: "darktealbaseboard_molding_wall_single",
		"left"		: "darktealbaseboard_molding_left",
		"right"		: "darktealbaseboard_molding_left,FLIP",
		"left_open"	: "darktealbaseboard_molding_left_open",
		"left_divide"	: "darktealbaseboard_molding_left_divide",
		"right_divide"	: "darktealbaseboard_molding_left_divide,FLIP",
		"swatch"	: "darktealbaseboard_molding_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"dark_uralia"			: {
		"name"		: "Dark Uralia Wallpaper",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "dark_uralia_wall",
		"wall_2"	: "dark_uralia_wall_2",
		"wall_3"	: "dark_uralia_wall_3",
		"wall_4"	: "dark_uralia_wall_4",
		"wall_5"	: "dark_uralia_wall_5",
		"wall_6"	: "dark_uralia_wall_6",
		"wall_left"	: "dark_uralia_wall_left",
		"wall_right"	: "dark_uralia_wall_right",
		"wall_single"	: "dark_uralia_wall_single",
		"left"		: "dark_uralia_left",
		"right"		: "dark_uralia_right",
		"left_open"	: "dark_uralia_left_open",
		"left_divide"	: "dark_uralia_right_divide,FLIP",
		"right_divide"	: "dark_uralia_right_divide",
		"swatch"	: "dark_uralia_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: true,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"grey_unfinished"		: {
		"name"		: "Drywall",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "grey_unfinished_wall",
		"wall_left"	: "grey_unfinished_wall",
		"wall_right"	: "grey_unfinished_wall",
		"wall_single"	: "grey_unfinished_wall",
		"left"		: "grey_unfinished_left",
		"right"		: "grey_unfinished_left,FLIP",
		"left_open"	: "grey_unfinished_left_open",
		"left_divide"	: "grey_unfinished_left_divide",
		"right_divide"	: "grey_unfinished_left_divide,FLIP",
		"swatch"	: "grey_unfinished_swatch",
		"cost_credits"	: 0,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: true
	},
	"fabric_sky"			: {
		"name"		: "Fabric Sky Wallpaper",
		"category"	: "Fun",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "fabric_sky_wall",
		"wall_2"	: "fabric_sky_wall_2",
		"wall_3"	: "fabric_sky_wall_3",
		"wall_4"	: "fabric_sky_wall_4",
		"wall_left"	: "fabric_sky_wall_left",
		"wall_right"	: "fabric_sky_wall_left,FLIP",
		"wall_single"	: "fabric_sky_wall",
		"left"		: "fabric_sky_left",
		"right"		: "fabric_sky_left,FLIP",
		"left_open"	: "fabric_sky_left_open",
		"left_divide"	: "fabric_sky_left_divide",
		"right_divide"	: "fabric_sky_left_divide,FLIP",
		"swatch"	: "fabric_sky_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"lackblue_stucco"		: {
		"name"		: "Faded Aquamarine Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "lackblue_stucco_wall",
		"wall_left"	: "lackblue_stucco_wall",
		"wall_right"	: "lackblue_stucco_wall",
		"wall_single"	: "lackblue_stucco_wall",
		"left"		: "lackblue_stucco_left",
		"right"		: "lackblue_stucco_left,FLIP",
		"left_open"	: "lackblue_stucco_left_open",
		"left_divide"	: "lackblue_stucco_left_divide",
		"right_divide"	: "lackblue_stucco_left_divide,FLIP",
		"swatch"	: "lackblue_stucco_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"tealgreen_molding"		: {
		"name"		: "Faded Aquamarine Stucco with Pillars",
		"category"	: "Traditional",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "tealgreen_molding_wall",
		"wall_left"	: "tealgreen_molding_wall_left",
		"wall_right"	: "tealgreen_molding_wall_right",
		"wall_single"	: "tealgreen_molding_wall_single",
		"left"		: "tealgreen_molding_left",
		"right"		: "tealgreen_molding_right",
		"left_open"	: "tealgreen_molding_left_open",
		"left_divide"	: "tealgreen_molding_left_divide",
		"right_divide"	: "tealgreen_molding_right_divide",
		"swatch"	: "tealgreen_molding_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"goldyellow_stucco"		: {
		"name"		: "Gold Yellow Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "goldyellow_stucco_wall",
		"wall_left"	: "goldyellow_stucco_wall",
		"wall_right"	: "goldyellow_stucco_wall",
		"wall_single"	: "goldyellow_stucco_wall",
		"left"		: "goldyellow_stucco_left",
		"right"		: "goldyellow_stucco_left,FLIP",
		"left_open"	: "goldyellow_stucco_left_open",
		"left_divide"	: "goldyellow_stucco_left_divide",
		"right_divide"	: "goldyellow_stucco_left_divide,FLIP",
		"swatch"	: "goldyellow_stucco_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"green_stripes"			: {
		"name"		: "Green Striped Wall",
		"category"	: "Stripes",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "green_stripes_wall",
		"wall_left"	: "green_stripes_wall",
		"wall_right"	: "green_stripes_wall",
		"wall_single"	: "green_stripes_wall",
		"left"		: "green_stripes_left",
		"right"		: "green_stripes_right",
		"left_open"	: "green_stripes_left_open",
		"left_divide"	: "green_stripes_left_divide",
		"right_divide"	: "green_stripes_right_divide",
		"swatch"	: "green_stripes_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"grey_brick"			: {
		"name"		: "Grey Brick Wall",
		"category"	: "Brick",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "grey_brick_wall",
		"wall_left"	: "grey_brick_wall",
		"wall_right"	: "grey_brick_wall",
		"wall_single"	: "grey_brick_wall",
		"left"		: "grey_brick_left",
		"right"		: "grey_brick_left,FLIP",
		"left_open"	: "grey_brick_left_open",
		"left_divide"	: "grey_brick_left_divide",
		"right_divide"	: "grey_brick_left_divide,FLIP",
		"swatch"	: "grey_brick_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"grey_stripes"			: {
		"name"		: "Grey Striped Walls",
		"category"	: "Stripes",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "grey_stripes_wall",
		"wall_left"	: "grey_stripes_wall",
		"wall_right"	: "grey_stripes_wall",
		"wall_single"	: "grey_stripes_wall",
		"left"		: "grey_stripes_left",
		"right"		: "grey_stripes_right",
		"left_open"	: "grey_stripes_left_open",
		"left_divide"	: "grey_stripes_left_divide",
		"right_divide"	: "grey_stripes_right_divide",
		"swatch"	: "grey_stripes_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"grey_stucco"			: {
		"name"		: "Grey Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "grey_stucco_wall",
		"wall_left"	: "grey_stucco_wall",
		"wall_right"	: "grey_stucco_wall",
		"wall_single"	: "grey_stucco_wall",
		"left"		: "grey_stucco_left",
		"right"		: "grey_stucco_left,FLIP",
		"left_open"	: "grey_stucco_left_open",
		"left_divide"	: "grey_stucco_left_divide",
		"right_divide"	: "grey_stucco_left_divide,FLIP",
		"swatch"	: "grey_stucco_swatch",
		"cost_credits"	: 0,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"grey_molding"			: {
		"name"		: "Grey Stucco with Molding",
		"category"	: "Traditional",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "grey_molding_wall",
		"wall_left"	: "grey_molding_wall_left",
		"wall_right"	: "grey_molding_wall_right",
		"wall_single"	: "grey_molding_wall_single",
		"left"		: "grey_molding_left",
		"right"		: "grey_molding_left,FLIP",
		"left_open"	: "grey_molding_left_open",
		"left_divide"	: "grey_molding_left_divide",
		"right_divide"	: "grey_molding_left_divide,FLIP",
		"swatch"	: "grey_molding_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"hell_fire"			: {
		"name"		: "Hell-ish Wallpaper",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "hell_fire_wall",
		"wall_2"	: "hell_fire_wall_2",
		"wall_3"	: "hell_fire_wall_3",
		"wall_4"	: "hell_fire_wall_4",
		"wall_5"	: "hell_fire_wall_5",
		"wall_left"	: "hell_fire_wall_left",
		"wall_right"	: "hell_fire_wall_left,FLIP",
		"wall_single"	: "hell_fire_wall_single",
		"left"		: "hell_fire_left",
		"right"		: "hell_fire_left,FLIP",
		"left_open"	: "hell_fire_left_open",
		"left_divide"	: "hell_fire_left_divide",
		"right_divide"	: "hell_fire_left_divide,FLIP",
		"swatch"	: "hell_fire_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: true,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"lime_stucco"			: {
		"name"		: "Key Lime Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "lime_stucco_wall",
		"wall_left"	: "lime_stucco_wall",
		"wall_right"	: "lime_stucco_wall",
		"wall_single"	: "lime_stucco_wall",
		"left"		: "lime_stucco_left",
		"right"		: "lime_stucco_left,FLIP",
		"left_open"	: "lime_stucco_left_open",
		"left_divide"	: "lime_stucco_left_divide",
		"right_divide"	: "lime_stucco_left_divide,FLIP",
		"swatch"	: "lime_stucco_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"blue_stucco"			: {
		"name"		: "Light Blue Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "blue_stucco_wall",
		"wall_left"	: "blue_stucco_wall",
		"wall_right"	: "blue_stucco_wall",
		"wall_single"	: "blue_stucco_wall",
		"left"		: "blue_stucco_left",
		"right"		: "blue_stucco_left,FLIP",
		"left_open"	: "blue_stucco_left_open",
		"left_divide"	: "blue_stucco_left_divide",
		"right_divide"	: "blue_stucco_left_divide,FLIP",
		"swatch"	: "blue_stucco_swatch",
		"cost_credits"	: 0,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: true
	},
	"cave"				: {
		"name"		: "Mossy Cave Walls",
		"category"	: "Nature",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "cave_wall",
		"wall_2"	: "cave_wall_2",
		"wall_3"	: "cave_wall_3",
		"wall_4"	: "cave_wall_4",
		"wall_5"	: "cave_wall_5",
		"wall_6"	: "cave_wall_6",
		"wall_left"	: "cave_wall_left",
		"wall_right"	: "cave_wall_right",
		"wall_single"	: "cave_wall_single",
		"left"		: "cave_left",
		"right"		: "cave_right",
		"left_open"	: "cave_left_open",
		"left_divide"	: "cave_left_divide",
		"right_divide"	: "cave_right_divide",
		"swatch"	: "cave_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"navy_stucco"			: {
		"name"		: "Navy Blue Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "navy_stucco_wall",
		"wall_left"	: "navy_stucco_wall",
		"wall_right"	: "navy_stucco_wall",
		"wall_single"	: "navy_stucco_wall",
		"left"		: "navy_stucco_left",
		"right"		: "navy_stucco_left,FLIP",
		"left_open"	: "navy_stucco_left_open",
		"left_divide"	: "navy_stucco_left_divide",
		"right_divide"	: "navy_stucco_left_divide,FLIP",
		"swatch"	: "navy_stucco_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"navy_molding"			: {
		"name"		: "Navy Blue Stucco with Molding",
		"category"	: "Traditional",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "navy_molding_wall",
		"wall_left"	: "navy_molding_wall_left",
		"wall_right"	: "navy_molding_wall_right",
		"wall_single"	: "navy_molding_wall_single",
		"left"		: "navy_molding_left",
		"right"		: "navy_molding_left,FLIP",
		"left_open"	: "navy_molding_left_open",
		"left_divide"	: "navy_molding_left_divide",
		"right_divide"	: "navy_molding_left_divide,FLIP",
		"swatch"	: "navy_molding_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"olive_stucco"			: {
		"name"		: "Olive Green Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "olive_stucco_wall",
		"wall_left"	: "olive_stucco_wall",
		"wall_right"	: "olive_stucco_wall",
		"wall_single"	: "olive_stucco_wall",
		"left"		: "olive_stucco_left",
		"right"		: "olive_stucco_left,FLIP",
		"left_open"	: "olive_stucco_left_open",
		"left_divide"	: "olive_stucco_left_divide",
		"right_divide"	: "olive_stucco_left_divide,FLIP",
		"swatch"	: "olive_stucco_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"orange_tiles"			: {
		"name"		: "Orange Tiles",
		"category"	: "Tiles",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "orange_tiles_wall",
		"wall_left"	: "orange_tiles_wall",
		"wall_right"	: "orange_tiles_wall",
		"wall_single"	: "orange_tiles_wall",
		"left"		: "orange_tiles_left",
		"right"		: "orange_tiles_left,FLIP",
		"left_open"	: "orange_tiles_left_open",
		"left_divide"	: "orange_tiles_left_divide",
		"right_divide"	: "orange_tiles_left_divide,FLIP",
		"swatch"	: "orange_tiles_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"lightblue_stucco"		: {
		"name"		: "Pale Blue Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "lightblue_stucco_wall",
		"wall_left"	: "lightblue_stucco_wall",
		"wall_right"	: "lightblue_stucco_wall",
		"wall_single"	: "lightblue_stucco_wall",
		"left"		: "lightblue_stucco_left",
		"right"		: "lightblue_stucco_left,FLIP",
		"left_open"	: "lightblue_stucco_left_open",
		"left_divide"	: "lightblue_stucco_left_divide",
		"right_divide"	: "lightblue_stucco_left_divide,FLIP",
		"swatch"	: "lightblue_stucco_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: true
	},
	"babyblue_molding"		: {
		"name"		: "Pale Blue Stucco with Molding",
		"category"	: "Traditional",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "babyblue_molding_wall",
		"wall_left"	: "babyblue_molding_wall_left",
		"wall_right"	: "babyblue_molding_wall_right",
		"wall_single"	: "babyblue_molding_wall_single",
		"left"		: "babyblue_molding_left",
		"right"		: "babyblue_molding_left,FLIP",
		"left_open"	: "babyblue_molding_left_open",
		"left_divide"	: "babyblue_molding_left_divide",
		"right_divide"	: "babyblue_molding_left_divide,FLIP",
		"swatch"	: "babyblue_molding_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"bluepillar_molding"		: {
		"name"		: "Pale Blue Stucco with Pillars",
		"category"	: "Traditional",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "bluepillar_molding_wall",
		"wall_left"	: "bluepillar_molding_wall_left",
		"wall_right"	: "bluepillar_molding_wall_right",
		"wall_single"	: "bluepillar_molding_wall_single",
		"left"		: "bluepillar_molding_left",
		"right"		: "bluepillar_molding_right",
		"left_open"	: "bluepillar_molding_left_open",
		"left_divide"	: "bluepillar_molding_left_divide",
		"right_divide"	: "bluepillar_molding_right_divide",
		"swatch"	: "bluepillar_molding_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"kids_room"			: {
		"name"		: "Paper Monster Walls",
		"category"	: "Fun",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "kids_room_wall",
		"wall_left"	: "kids_room_wall",
		"wall_right"	: "kids_room_wall",
		"wall_single"	: "kids_room_wall",
		"left"		: "kids_room_left",
		"right"		: "kids_room_left,FLIP",
		"left_open"	: "kids_room_left_open",
		"left_divide"	: "kids_room_left_divide",
		"right_divide"	: "kids_room_left_divide,FLIP",
		"swatch"	: "kids_room_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"club_light"			: {
		"name"		: "Pastel Glow Wallpaper",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "club_light_wall",
		"wall_left"	: "club_light_wall",
		"wall_right"	: "club_light_wall",
		"wall_single"	: "club_light_wall",
		"left"		: "club_light_left",
		"right"		: "club_light_left,FLIP",
		"left_open"	: "club_light_left_open",
		"left_divide"	: "club_light_left_divide",
		"right_divide"	: "club_light_left_divide,FLIP",
		"swatch"	: "club_light_swatch",
		"cost_credits"	: 25,
		"is_visible"	: false,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"yellowgreen_stucco"		: {
		"name"		: "Pine Glade Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "yellowgreen_stucco_wall",
		"wall_left"	: "yellowgreen_stucco_wall",
		"wall_right"	: "yellowgreen_stucco_wall",
		"wall_single"	: "yellowgreen_stucco_wall",
		"left"		: "yellowgreen_stucco_left",
		"right"		: "yellowgreen_stucco_left,FLIP",
		"left_open"	: "yellowgreen_stucco_left_open",
		"left_divide"	: "yellowgreen_stucco_left_divide",
		"right_divide"	: "yellowgreen_stucco_left_divide,FLIP",
		"swatch"	: "yellowgreen_stucco_swatch",
		"cost_credits"	: 0,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"yellowgreen_molding"		: {
		"name"		: "Pine Glade Stucco with Molding",
		"category"	: "Traditional",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "yellowgreen_molding_wall",
		"wall_left"	: "yellowgreen_molding_wall_left",
		"wall_right"	: "yellowgreen_molding_wall_right",
		"wall_single"	: "yellowgreen_molding_wall_single",
		"left"		: "yellowgreen_molding_left",
		"right"		: "yellowgreen_molding_left,FLIP",
		"left_open"	: "yellowgreen_molding_left_open",
		"left_divide"	: "yellowgreen_molding_left_divide",
		"right_divide"	: "yellowgreen_molding_left_divide,FLIP",
		"swatch"	: "yellowgreen_molding_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"pink_heart"			: {
		"name"		: "Pink Heart Wallpaper",
		"category"	: "Stripes",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "pink_heartstripes_wall",
		"wall_left"	: "pink_heartstripes_wall",
		"wall_right"	: "pink_heartstripes_wall",
		"wall_single"	: "pink_heartstripes_wall",
		"left"		: "pink_heartstripes_left",
		"right"		: "pink_heartstripes_left,FLIP",
		"left_open"	: "pink_heartstripes_left_open",
		"left_divide"	: "pink_heartstripes_left_divide",
		"right_divide"	: "pink_heartstripes_left_divide,FLIP",
		"swatch"	: "pink_heartstripes_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"pink_stucco"			: {
		"name"		: "Pink Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "pink_stucco_wall",
		"wall_left"	: "pink_stucco_wall",
		"wall_right"	: "pink_stucco_wall",
		"wall_single"	: "pink_stucco_wall",
		"left"		: "pink_stucco_left",
		"right"		: "pink_stucco_left,FLIP",
		"left_open"	: "pink_stucco_left_open",
		"left_divide"	: "pink_stucco_left_divide",
		"right_divide"	: "pink_stucco_left_divide,FLIP",
		"swatch"	: "pink_stucco_swatch",
		"cost_credits"	: 0,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"purple_stripes"		: {
		"name"		: "Purple Striped Wall",
		"category"	: "Stripes",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "purple_stripes_wall",
		"wall_left"	: "purple_stripes_wall",
		"wall_right"	: "purple_stripes_wall",
		"wall_single"	: "purple_stripes_wall",
		"left"		: "purple_stripes_left",
		"right"		: "purple_stripes_left,FLIP",
		"left_open"	: "purple_stripes_left_open",
		"left_divide"	: "purple_stripes_left_divide",
		"right_divide"	: "purple_stripes_right_divide",
		"swatch"	: "purple_stripes_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"longred_brick"			: {
		"name"		: "Red Brick Wall",
		"category"	: "Brick",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "longred_brick_wall",
		"wall_left"	: "longred_brick_wall",
		"wall_right"	: "longred_brick_wall",
		"wall_single"	: "longred_brick_wall",
		"left"		: "longred_brick_left",
		"right"		: "longred_brick_left,FLIP",
		"left_open"	: "longred_brick_left_open",
		"left_divide"	: "longred_brick_left_divide",
		"right_divide"	: "longred_brick_left_divide,FLIP",
		"swatch"	: "longred_brick_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"red_darkcreepy"		: {
		"name"		: "Red Creepy Wall Panels",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "red_darkcreepy_wall",
		"wall_left"	: "red_darkcreepy_wall_left",
		"wall_right"	: "red_darkcreepy_wall_right",
		"wall_single"	: "red_darkcreepy_wall_single",
		"left"		: "red_darkcreepy_left",
		"right"		: "red_darkcreepy_left,FLIP",
		"left_open"	: "red_darkcreepy_left_open",
		"left_divide"	: "red_darkcreepy_left_divide",
		"right_divide"	: "red_darkcreepy_left_divide,FLIP",
		"swatch"	: "red_darkcreepy_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: true,
		"is_default"	: false
	},
	"rock_cave"			: {
		"name"		: "Rock Cave Walls",
		"category"	: "Nature",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "rock_cave_wall",
		"wall_2"	: "rock_cave_wall_2",
		"wall_3"	: "rock_cave_wall_3",
		"wall_4"	: "rock_cave_wall_4",
		"wall_5"	: "rock_cave_wall_5",
		"wall_6"	: "rock_cave_wall_6",
		"wall_left"	: "rock_cave_wall_left",
		"wall_right"	: "rock_cave_wall_right",
		"wall_single"	: "rock_cave_wall_single",
		"left"		: "rock_cave_left",
		"right"		: "rock_cave_right",
		"left_open"	: "rock_cave_left_open",
		"left_divide"	: "rock_cave_left_divide",
		"right_divide"	: "rock_cave_right_divide",
		"swatch"	: "rock_cave_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"heartred_stucco"		: {
		"name"		: "Rose Fog Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "heartred_stucco_wall",
		"wall_left"	: "heartred_stucco_wall",
		"wall_right"	: "heartred_stucco_wall",
		"wall_single"	: "heartred_stucco_wall",
		"left"		: "heartred_stucco_left",
		"right"		: "heartred_stucco_left,FLIP",
		"left_open"	: "heartred_stucco_left_open",
		"left_divide"	: "heartred_stucco_left_divide",
		"right_divide"	: "heartred_stucco_left_divide,FLIP",
		"swatch"	: "heartred_stucco_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"coralpillar_molding"		: {
		"name"		: "Rose Fog Stucco with Pillars",
		"category"	: "Traditional",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "coralpillar_molding_wall",
		"wall_left"	: "coralpillar_molding_wall_left",
		"wall_right"	: "coralpillar_molding_wall_right",
		"wall_single"	: "coralpillar_molding_wall_single",
		"left"		: "coralpillar_molding_left",
		"right"		: "coralpillar_molding_right",
		"left_open"	: "coralpillar_molding_left_open",
		"left_divide"	: "coralpillar_molding_left_divide",
		"right_divide"	: "coralpillar_molding_right_divide",
		"swatch"	: "coralpillar_molding_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"spaceship"			: {
		"name"		: "Spaceship Wall Panels",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "spaceship_wall",
		"wall_left"	: "spaceship_wall",
		"wall_right"	: "spaceship_wall",
		"wall_single"	: "spaceship_wall",
		"left"		: "spaceship_left",
		"right"		: "spaceship_left,FLIP",
		"left_open"	: "spaceship_left_open",
		"left_divide"	: "spaceship_left_divide",
		"right_divide"	: "spaceship_left_divide,FLIP",
		"swatch"	: "spaceship_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"spanishred_stucco"		: {
		"name"		: "Spanish Red Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "spanishred_stucco_wall",
		"wall_left"	: "spanishred_stucco_wall",
		"wall_right"	: "spanishred_stucco_wall",
		"wall_single"	: "spanishred_stucco_wall",
		"left"		: "spanishred_stucco_left",
		"right"		: "spanishred_stucco_left,FLIP",
		"left_open"	: "spanishred_stucco_left_open",
		"left_divide"	: "spanishred_stucco_left_divide",
		"right_divide"	: "spanishred_stucco_left_divide,FLIP",
		"swatch"	: "spanishred_stucco_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"red_molding"			: {
		"name"		: "Spanish Red Stucco with Molding",
		"category"	: "Traditional",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "red_molding_wall",
		"wall_left"	: "red_molding_wall_left",
		"wall_right"	: "red_molding_wall_right",
		"wall_single"	: "red_molding_wall_single",
		"left"		: "red_molding_left",
		"right"		: "red_molding_left,FLIP",
		"left_open"	: "red_molding_left_open",
		"left_divide"	: "red_molding_left_divide",
		"right_divide"	: "red_molding_left_divide,FLIP",
		"swatch"	: "red_molding_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"star_darksky_wallpaper"	: {
		"name"		: "Starry Sky Wallpaper",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "star_darksky_wall",
		"wall_left"	: "star_darksky_wall",
		"wall_right"	: "star_darksky_wall",
		"wall_single"	: "star_darksky_wall",
		"left"		: "star_darksky_left",
		"right"		: "star_darksky_right",
		"left_open"	: "star_darksky_left_open",
		"left_divide"	: "star_darksky_left_divide",
		"right_divide"	: "star_darksky_right_divide",
		"swatch"	: "star_darksky_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"sweetpuple_stucco"		: {
		"name"		: "Sweet Purple Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "sweetpuple_stucco_wall",
		"wall_left"	: "sweetpuple_stucco_wall",
		"wall_right"	: "sweetpuple_stucco_wall",
		"wall_single"	: "sweetpuple_stucco_wall",
		"left"		: "sweetpuple_stucco_left",
		"right"		: "sweetpuple_stucco_left,FLIP",
		"left_open"	: "sweetpuple_stucco_left_open",
		"left_divide"	: "sweetpuple_stucco_left_divide",
		"right_divide"	: "sweetpuple_stucco_left_divide,FLIP",
		"swatch"	: "sweetpuple_stucco_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"white_stars"			: {
		"name"		: "Tiny Stars Wallpaper",
		"category"	: "Fun",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "white_small_stars_wall",
		"wall_left"	: "white_small_stars_wall",
		"wall_right"	: "white_small_stars_wall",
		"wall_single"	: "white_small_stars_wall",
		"left"		: "white_small_stars_left",
		"right"		: "white_small_stars_left,FLIP",
		"left_open"	: "white_small_stars_left_open",
		"left_divide"	: "white_small_stars_left_divide",
		"right_divide"	: "white_small_stars_left_divide,FLIP",
		"swatch"	: "white_small_stars_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"uralia_wallpaper"		: {
		"name"		: "Uralia Wallpaper",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "uralia_wall",
		"wall_2"	: "uralia_wall_2",
		"wall_3"	: "uralia_wall_3",
		"wall_4"	: "uralia_wall_4",
		"wall_5"	: "uralia_wall_5",
		"wall_6"	: "uralia_wall_6",
		"wall_left"	: "uralia_wall",
		"wall_right"	: "uralia_wall",
		"wall_single"	: "uralia_wall",
		"left"		: "uralia_left",
		"right"		: "uralia_left,FLIP",
		"left_open"	: "uralia_left_open",
		"left_divide"	: "uralia_left_divide",
		"right_divide"	: "uralia_left_divide,FLIP",
		"swatch"	: "uralia_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: true,
		"is_default"	: false
	},
	"white_stucco"			: {
		"name"		: "White Stucco",
		"category"	: "Plain",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "white_stucco_wall",
		"wall_left"	: "white_stucco_wall",
		"wall_right"	: "white_stucco_wall",
		"wall_single"	: "white_stucco_wall",
		"left"		: "white_stucco_left",
		"right"		: "white_stucco_left,FLIP",
		"left_open"	: "white_stucco_left_open",
		"left_divide"	: "white_stucco_left_divide",
		"right_divide"	: "white_stucco_left_divide,FLIP",
		"swatch"	: "white_stucco_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"creamybaseboard_molding"	: {
		"name"		: "White Stucco with Charcoal Wainscoting",
		"category"	: "Traditional",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "creamybaseboard_molding_wall",
		"wall_left"	: "creamybaseboard_molding_wall_left",
		"wall_right"	: "creamybaseboard_molding_wall_right",
		"wall_single"	: "creamybaseboard_molding_wall_single",
		"left"		: "creamybaseboard_molding_left",
		"right"		: "creamybaseboard_molding_left,FLIP",
		"left_open"	: "creamybaseboard_molding_left_open",
		"left_divide"	: "creamybaseboard_molding_left_divide",
		"right_divide"	: "creamybaseboard_molding_left_divide,FLIP",
		"swatch"	: "creamybaseboard_molding_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"whitepillar_molding"		: {
		"name"		: "White Stucco with Pillars",
		"category"	: "Traditional",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "whitepillar_molding_wall",
		"wall_left"	: "whitepillar_molding_wall_left",
		"wall_right"	: "whitepillar_molding_wall_right",
		"wall_single"	: "whitepillar_molding_wall_single",
		"left"		: "whitepillar_molding_left",
		"right"		: "whitepillar_molding_right",
		"left_open"	: "whitepillar_molding_left_open",
		"left_divide"	: "whitepillar_molding_left_divide",
		"right_divide"	: "whitepillar_molding_right_divide",
		"swatch"	: "whitepillar_molding_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"wooden_cave"			: {
		"name"		: "Wooden Cave Walls",
		"category"	: "Wood",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "wooden_cave_wall",
		"wall_2"	: "wooden_cave_wall_2",
		"wall_3"	: "wooden_cave_wall_3",
		"wall_4"	: "wooden_cave_wall_4",
		"wall_5"	: "wooden_cave_wall_5",
		"wall_6"	: "wooden_cave_wall_6",
		"wall_left"	: "wooden_cave_wall_left",
		"wall_right"	: "wooden_cave_wall_right",
		"wall_single"	: "wooden_cave_wall_single",
		"left"		: "wooden_cave_left",
		"right"		: "wooden_cave_right",
		"left_open"	: "wooden_cave_left_open",
		"left_divide"	: "wooden_cave_left_divide",
		"right_divide"	: "wooden_cave_right_divide",
		"swatch"	: "wooden_cave_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"red_brick"			: {
		"name"		: "Yaletown Brick Wall",
		"category"	: "Brick",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "red_brick_wall",
		"wall_left"	: "red_brick_wall",
		"wall_right"	: "red_brick_wall",
		"wall_single"	: "red_brick_wall",
		"left"		: "red_brick_left",
		"right"		: "red_brick_left,FLIP",
		"left_open"	: "red_brick_left_open",
		"left_divide"	: "red_brick_left_divide",
		"right_divide"	: "red_brick_left_divide,FLIP",
		"swatch"	: "red_brick_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"yellow_boghouse"		: {
		"name"		: "Yellow Bog Wallpaper",
		"category"	: "Wood",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"wall"		: "yellow_boghouse_wall",
		"wall_2"	: "yellow_boghouse_wall_2",
		"wall_3"	: "yellow_boghouse_wall_3",
		"wall_4"	: "yellow_boghouse_wall_4",
		"wall_5"	: "yellow_boghouse_wall_5",
		"wall_left"	: "yellow_boghouse_wall",
		"wall_right"	: "yellow_boghouse_wall",
		"wall_single"	: "yellow_boghouse_wall",
		"left"		: "yellow_boghouse_left",
		"right"		: "yellow_boghouse_left,FLIP",
		"left_open"	: "yellow_boghouse_left_open",
		"left_divide"	: "yellow_boghouse_left_divide",
		"right_divide"	: "yellow_boghouse_left_divide,FLIP",
		"swatch"	: "yellow_boghouse_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"sea_wallpaper"			: {
		"name"		: "Underwater Landscape Wallpaper",
		"category"	: "Nature",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 9970,
		"wall"		: "Sea_Wall",
		"wall_left"	: "Sea_wall_left",
		"wall_right"	: "Sea_wall_right",
		"wall_single"	: "Sea_wall_single",
		"left"		: "Sea_left",
		"right"		: "Sea_left,FLIP",
		"left_open"	: "Sea_left_open",
		"left_divide"	: "Sea_left_divide",
		"right_divide"	: "Sea_left_divide,FLIP",
		"swatch"	: "Sea_swatch",
		"cost_credits"	: 75,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"yellow_cubimal"		: {
		"name"		: "Yellow Cubimal Wallpaper",
		"category"	: "Fun",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 9979,
		"wall"		: "yellow_cubimal_wall",
		"wall_left"	: "yellow_cubimal_wall",
		"wall_right"	: "yellow_cubimal_wall",
		"wall_single"	: "yellow_cubimal_wall",
		"left"		: "yellow_cubimal_left",
		"right"		: "yellow_cubimal_left,FLIP",
		"left_open"	: "yellow_cubimal_left_open",
		"left_divide"	: "yellow_cubimal_left_divide",
		"right_divide"	: "yellow_cubimal_left_divide,FLIP",
		"swatch"	: "yellow_cubimal_swatch",
		"cost_credits"	: 75,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: true,
		"is_default"	: false
	},
	"pink_cubimal"			: {
		"name"		: "Pink Cubimal Wallpaper",
		"category"	: "Fun",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 9980,
		"wall"		: "pink_cubimal_wall",
		"wall_left"	: "pink_cubimal_wall",
		"wall_right"	: "pink_cubimal_wall",
		"wall_single"	: "pink_cubimal_wall",
		"left"		: "pink_cubimal_left",
		"right"		: "pink_cubimal_left,FLIP",
		"left_open"	: "pink_cubimal_left_open",
		"left_divide"	: "pink_cubimal_left_divide",
		"right_divide"	: "pink_cubimal_left_divide,FLIP",
		"swatch"	: "pink_cubimal_swatch",
		"cost_credits"	: 75,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: true,
		"is_default"	: false
	},
	"bacon"				: {
		"name"		: "Bacon Covered Wall",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 9990,
		"wall"		: "bacon_wall",
		"wall_2"	: "bacon_wall_2",
		"wall_left"	: "bacon_wall",
		"wall_right"	: "bacon_wall",
		"wall_single"	: "bacon_wall",
		"left"		: "bacon_left",
		"right"		: "bacon_left,FLIP",
		"left_open"	: "bacon_left_open",
		"left_divide"	: "bacon_left_divide",
		"right_divide"	: "bacon_left_divide,FLIP",
		"swatch"	: "bacon_swatch",
		"cost_credits"	: 75,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"rook_forest_line"		: {
		"name"		: "Rook Forest Wallpaper",
		"category"	: "Nature",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 9998,
		"wall"		: "rook_forest_line_wall",
		"wall_2"	: "rook_forest_line_wall_2",
		"wall_3"	: "rook_forest_line_wall_3",
		"wall_4"	: "rook_forest_line_wall_4",
		"wall_5"	: "rook_forest_line_wall_5",
		"wall_6"	: "rook_forest_line_wall_6",
		"wall_left"	: "rook_forest_line_wall",
		"wall_right"	: "rook_forest_line_wall",
		"wall_single"	: "rook_forest_line_wall",
		"left"		: "rook_forest_line_left",
		"right"		: "rook_forest_line_right",
		"left_open"	: "rook_forest_line_left_open",
		"left_divide"	: "rook_forest_line_left_divide",
		"right_divide"	: "rook_forest_line_right_divide",
		"swatch"	: "rook_forest_line_swatch",
		"cost_credits"	: 75,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"wooden_vege_broccoli"		: {
		"name"		: "Broccoli Forest Wallpaper",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 9999,
		"wall"		: "wooden_vege_broccoli_wall",
		"wall_2"	: "wooden_vege_broccoli_wall_2",
		"wall_3"	: "wooden_vege_broccoli_wall_3",
		"wall_4"	: "wooden_vege_broccoli_wall_4",
		"wall_5"	: "wooden_vege_broccoli_wall_5",
		"wall_6"	: "wooden_vege_broccoli_wall_6",
		"wall_left"	: "wooden_vege_broccoli_wall_left",
		"wall_right"	: "wooden_vege_broccoli_wall_right",
		"wall_single"	: "wooden_vege_broccoli_wall_single",
		"left"		: "wooden_vege_broccoli_left",
		"right"		: "wooden_vege_broccoli_right",
		"left_open"	: "wooden_vege_broccoli_left_open",
		"left_divide"	: "wooden_vege_broccoli_left_divide",
		"right_divide"	: "wooden_vege_broccoli_right_divide",
		"swatch"	: "wooden_vege_broccoli_swatch",
		"cost_credits"	: 75,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"ioletoyageky"			: {
		"name"		: "Violet Voyage Wallpaper",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 10000,
		"wall"		: "violetvoyagesky_wall",
		"wall_left"	: "violetvoyagesky_wall",
		"wall_right"	: "violetvoyagesky_wall",
		"wall_single"	: "violetvoyagesky_wall",
		"left"		: "violetvoyagesky_left",
		"right"		: "violetvoyagesky_left,FLIP",
		"left_open"	: "violetvoyagesky_left_open",
		"left_divide"	: "violetvoyagesky_left_divide",
		"right_divide"	: "violetvoyagesky_left_divide,FLIP",
		"swatch"	: "violetvoyagesky_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: true,
		"is_default"	: false
	}
};

var homes_floor_configs = {
	"bacon_floor"		: {
		"name"		: "Bacon Covered Floor",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "bacon_floor",
		"main_2"	: "bacon_floor_2",
		"left"		: "bacon_floor_left",
		"right"		: "bacon_floor",
		"swatch"	: "bacon_floor_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"beige_carpet"		: {
		"name"		: "Beige Berber Carpet",
		"category"	: "Carpet",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "beige_carpet_floor",
		"left"		: "beige_carpet_floor_left",
		"right"		: "beige_carpet_floor",
		"swatch"	: "beige_carpet_floor_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"brown_boghouse_floor"	: {
		"name"		: "Brown Bog Floor",
		"category"	: "Wood",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "brown_boghouse_floor",
		"left"		: "brown_boghouse_floor_left",
		"right"		: "brown_boghouse_floor",
		"swatch"	: "brown_boghouse_floor_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: true,
		"is_default"	: false
	},
	"darkstar_black_floor"	: {
		"name"		: "Dark Starry Sky Floor",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "darkstar_black_floor",
		"main_2"	: "darkstar_black_floor_2",
		"left"		: "darkstar_black_floor_left",
		"right"		: "darkstar_black_floor",
		"swatch"	: "darkstar_black_floor_swatch",
		"cost_credits"	: 25,
		"is_visible"	: false,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"darkuralia"		: {
		"name"		: "Dark Uralia Floor",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "dark_uralia_floor",
		"main_2"	: "dark_uralia_floor_2",
		"main_3"	: "dark_uralia_floor_3",
		"main_4"	: "dark_uralia_floor_4",
		"main_5"	: "dark_uralia_floor_5",
		"left"		: "dark_uralia_floor_left",
		"right"		: "dark_uralia_floor",
		"swatch"	: "dark_uralia_floor_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: true,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"woodpanel_2"		: {
		"name"		: "Dark Wood Paneling",
		"category"	: "Wood",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "woodpanel_2_floor",
		"left"		: "woodpanel_2_floor_left",
		"right"		: "woodpanel_2_floor",
		"swatch"	: "woodpanel_2_floor_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"grass_flower"		: {
		"name"		: "Grassy Floor",
		"category"	: "Nature",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "grass_flower_floor",
		"main_2"	: "grass_flower_floor_2",
		"main_3"	: "grass_flower_floor_3",
		"left"		: "grass_flower_floor_left",
		"right"		: "grass_flower_floor",
		"swatch"	: "grass_flower_floor_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"beige_carpet_blue"	: {
		"name"		: "Grey Gerber Carpet",
		"category"	: "Carpet",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "beige_carpet__blue_floor",
		"left"		: "beige_carpet_blue_floor_left",
		"right"		: "beige_carpet__blue_floor",
		"swatch"	: "grey_gerber_carpet_floor_swatch",
		"cost_credits"	: 0,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"greystone_floor"	: {
		"name"		: "Grey Stone Floor",
		"category"	: "Stone",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "greystone_floor",
		"left"		: "greystone_floor_left",
		"right"		: "greystone_floor",
		"swatch"	: "greystone_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"hell"			: {
		"name"		: "Hell-ish Floor",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "hell_floor",
		"main_2"	: "hell_floor_2",
		"main_3"	: "hell_floor_3",
		"main_4"	: "hell_floor_4",
		"main_5"	: "hell_floor_5",
		"left"		: "hell_floor_left",
		"right"		: "hell_floor",
		"swatch"	: "hell_floor_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: true,
		"is_subscriber"	: true,
		"is_default"	: false
	},
	"leopard_skin"		: {
		"name"		: "Leopard Carpet",
		"category"	: "Carpet",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "leopard_skin_floor",
		"left"		: "leopard_skin_floor_left",
		"right"		: "leopard_skin_floor",
		"swatch"	: "leopard_skin_floor_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"woodpanel_3_floor"	: {
		"name"		: "Light Wood Paneling",
		"category"	: "Wood",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "woodpanel_3_floor",
		"left"		: "woodpanel_3_floor_left",
		"right"		: "woodpanel_3_floor",
		"swatch"	: "woodpanel_3_floor_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"marble_floor"		: {
		"name"		: "Marble Floor",
		"category"	: "Stone",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "marble_floor",
		"left"		: "marble_floor_left",
		"right"		: "marble_floor",
		"swatch"	: "marble_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"marigold_carpet"	: {
		"name"		: "Marigold Carpet",
		"category"	: "Carpet",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "marigold_carpet_floor",
		"left"		: "marigold_carpet_floor_left",
		"right"		: "marigold_carpet_floor",
		"swatch"	: "marigold_carpet_floor_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: true,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"metal_spaceship_floor"	: {
		"name"		: "Metal Spaceship Floor",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "Metal_Floor",
		"left"		: "Metal_Floor_Left",
		"right"		: "Metal_Floor",
		"swatch"	: "Metal_Floor_Swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"moss"			: {
		"name"		: "Mossy Floor",
		"category"	: "Nature",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "moss_floor",
		"main_2"	: "moss_floor_2",
		"main_3"	: "moss_floor_3",
		"left"		: "moss_floor_left",
		"right"		: "moss_floor",
		"swatch"	: "moss_floor_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"rook_forestfloor"	: {
		"name"		: "Rook Forest Floor",
		"category"	: null,
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "rook_forest_floor_1",
		"main_2"	: "rook_forest_floor_2",
		"main_3"	: "rook_forest_floor_3",
		"main_4"	: "rook_forest_floor_4",
		"left"		: "rook_forest_floor_left",
		"right"		: "rook_forest_floor_1",
		"swatch"	: "rook_forest_floor_swatch",
		"cost_credits"	: 0,
		"is_visible"	: false,
		"is_new"	: true,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"sea_sand_floor"	: {
		"name"		: "Sandy Seascape Flooring",
		"category"	: "Nature",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "SeaSand_Floor",
		"left"		: "SeaSand_Floor_Left",
		"right"		: "SeaSand_Floor",
		"swatch"	: "SeaSand_Swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"snow_leopard_skin"	: {
		"name"		: "Snow Leopard Carpet",
		"category"	: "Carpet",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "snow_leopard_skin_floor",
		"left"		: "snow_leopard_skin_floor_left",
		"right"		: "snow_leopard_skin_floor",
		"swatch"	: "snow_leopard_skin_floor_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: true,
		"is_default"	: false
	},
	"sky_dark_floor"	: {
		"name"		: "Starry Sky Floor",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "sky_dark_floor",
		"left"		: "sky_dark_floor",
		"right"		: "sky_dark_floor",
		"swatch"	: "sky_dark_floor_swatch",
		"cost_credits"	: 25,
		"is_visible"	: false,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"starter_crappy"	: {
		"name"		: "Unfinished Flooring",
		"category"	: "Stone",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "starter_crappy_floor",
		"left"		: "starter_crappy_floor_left",
		"right"		: "starter_crappy_floor",
		"swatch"	: "starter_crappy_floor_swatch",
		"cost_credits"	: 0,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: true
	},
	"uralia_floor"		: {
		"name"		: "Uralia Grass Floor",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "uralia_floor",
		"main_2"	: "uralia_floor_2",
		"main_3"	: "uralia_floor_3",
		"main_4"	: "uralia_floor_4",
		"main_5"	: "uralia_floor_5",
		"main_6"	: "uralia_floor_6",
		"left"		: "uralia_floor_left",
		"right"		: "uralia_floor",
		"swatch"	: "uralia_floor_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: true,
		"is_default"	: false
	},
	"ioletoyage"		: {
		"name"		: "Violet Voyage Floor",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "violetvoyage_floor",
		"left"		: "violetvoyage_floor_left",
		"right"		: "violetvoyage_floor",
		"swatch"	: "violetvoyage_floor_swatch",
		"cost_credits"	: 55,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"wood_cave_floor"	: {
		"name"		: "Weathered Wood Floor",
		"category"	: "Wood",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "wood_cave_floor",
		"left"		: "wood_cave_floor_left",
		"right"		: "wood_cave_floor",
		"swatch"	: "wood_cave_floor_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"whitewood_floor"	: {
		"name"		: "White Wooden Floor",
		"category"	: "Wood",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "whitewood_floor",
		"main_2"	: "whitewood_floor_2",
		"main_3"	: "whitewood_floor_3",
		"main_4"	: "whitewood_floor_4",
		"main_5"	: "whitewood_floor_5",
		"main_6"	: "whitewood_floor_6",
		"left"		: "whitewood_floor_left",
		"right"		: "whitewood_floor",
		"swatch"	: "whitewood_floor_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"woodpanel"		: {
		"name"		: "Wood Paneling",
		"category"	: "Wood",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "woodpanel_1_floor",
		"left"		: "woodpanel_1_floor_left",
		"right"		: "woodpanel_1_floor",
		"swatch"	: "woodpanel_1_floor_swatch",
		"cost_credits"	: 0,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: true
	}
};

var homes_ceiling_configs = {
	"bacon_ceiling"			: {
		"name"		: "Bacon Covered Ceiling",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "bacon_ceiling",
		"left"		: "bacon_ceiling",
		"right"		: "bacon_ceiling",
		"swatch"	: "bacon_ceiling_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"brown_boghouse_ceiling"	: {
		"name"		: "Brown Bog Ceiling",
		"category"	: "Wood",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "brown_boghouse_ceiling",
		"left"		: "brown_boghouse_ceiling",
		"right"		: "brown_boghouse_ceiling",
		"swatch"	: "brown_boghouse_ceiling_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: true,
		"is_default"	: false
	},
	"darkconcrete"			: {
		"name"		: "Dark Concrete Ceiling",
		"category"	: "Concrete",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "darkconcrete_ceiling",
		"left"		: "darkconcrete_ceiling",
		"right"		: "darkconcrete_ceiling",
		"swatch"	: "darkconcrete_ceiling_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"darkstar_black_ceiling"	: {
		"name"		: "Dark Starry Sky Ceiling",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "darkstar_black_ceiling",
		"main_2"	: "darkstar_black_ceiling_2",
		"left"		: "darkstar_black_ceiling_left",
		"right"		: "darkstar_black_ceiling",
		"swatch"	: "darkstar_black_ceiling_swatch",
		"cost_credits"	: 25,
		"is_visible"	: false,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"dark_uraliaceiling"		: {
		"name"		: "Dark Uralia Ceiling",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "dark_uralia_ceiling",
		"main_2"	: "dark_uralia_ceiling_2",
		"main_3"	: "dark_uralia_ceiling_3",
		"left"		: "dark_uralia_ceiling",
		"right"		: "dark_uralia_ceiling",
		"swatch"	: "dark_uralia_ceiling_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: true,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"vege_ceiling"			: {
		"name"		: "Gentle Cloud Ceiling",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "vege_ceiling",
		"main_2"	: "vege_ceiling_2",
		"main_3"	: "vege_ceiling_3",
		"left"		: "vege_ceiling",
		"right"		: "vege_ceiling",
		"swatch"	: "vege_ceiling_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"grey_crappy_ceiling"		: {
		"name"		: "Grey Stucco Ceiling",
		"category"	: "Stucco",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "grey_crappy_ceiling",
		"left"		: "grey_crappy_ceiling",
		"right"		: "grey_crappy_ceiling",
		"swatch"	: "grey_crappy_ceiling_swatch",
		"cost_credits"	: 0,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"ceilingshell"			: {
		"name"		: "Hell-ish Ceiling",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "hell_ceiling",
		"left"		: "hell_ceiling",
		"right"		: "hell_ceiling",
		"swatch"	: "hell_ceiling_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: true,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"lightblue_crappy"		: {
		"name"		: "Light Blue Stucco Ceiling",
		"category"	: "Stucco",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "lightblue_crappy_ceiling",
		"left"		: "lightblue_crappy_ceiling",
		"right"		: "lightblue_crappy_ceiling",
		"swatch"	: "lightblue_crappy_ceiling_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"orange_crappy"			: {
		"name"		: "Orange Stucco Ceiling",
		"category"	: "Stucco",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "orange_crappy_ceiling",
		"left"		: "orange_crappy_ceiling",
		"right"		: "orange_crappy_ceiling",
		"swatch"	: "orange_crappy_ceiling_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"pink_crappy"			: {
		"name"		: "Pink Stucco Ceiling",
		"category"	: "Stucco",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "pink_crappy_ceiling",
		"left"		: "pink_crappy_ceiling",
		"right"		: "pink_crappy_ceiling",
		"swatch"	: "pink_crappy_ceiling_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"lime_crappy_ceiling"		: {
		"name"		: "Plain Lime Ceiling",
		"category"	: "Stucco",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "lime_crappy_ceiling",
		"left"		: "lime_crappy_ceiling",
		"right"		: "lime_crappy_ceiling",
		"swatch"	: "lime_crappy_ceiling_swatch",
		"cost_credits"	: 0,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"rook_forest"			: {
		"name"		: "Rook Forest Ceiling",
		"category"	: null,
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "rook_forest_ceiling_1",
		"main_2"	: "rook_forest_ceiling_2",
		"main_3"	: "rook_forest_ceiling_3",
		"main_4"	: "rook_forest_ceiling_4",
		"left"		: "rook_forest_ceiling_1",
		"right"		: "rook_forest_ceiling_1",
		"swatch"	: "rook_forest_ceiling_swatch",
		"cost_credits"	: 0,
		"is_visible"	: false,
		"is_new"	: true,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"spaceship_ceiling"		: {
		"name"		: "Spaceship Ceiling",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "SpaceShip_Ceililng",
		"left"		: "SpaceShip_Ceililng",
		"right"		: "SpaceShip_Ceililng",
		"swatch"	: "SpaceShip_Ceiling_Swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"dark_start"			: {
		"name"		: "Starry Sky Ceiling",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "dark_start_ceiling",
		"left"		: "dark_start_ceiling",
		"right"		: "dark_start_ceiling",
		"swatch"	: "dark_start_ceiling_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"test_greenhouse_ceiling"	: {
		"name"		: "Test Greenhouse Ceiling",
		"category"	: null,
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "test_greenhouse_ceiling",
		"left"		: "test_greenhouse_ceiling_left",
		"right"		: "test_greenhouse_ceiling_right",
		"swatch"	: "test_greenhouse_ceiling_swatch",
		"cost_credits"	: 0,
		"is_visible"	: false,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"turquoise_stucco"		: {
		"name"		: "Turquoise Stucco",
		"category"	: "Stucco",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "turquoise_stucco_ceiling",
		"left"		: "turquoise_stucco_ceiling",
		"right"		: "turquoise_stucco_ceiling",
		"swatch"	: "turquoise_stucco_ceiling_swatch",
		"cost_credits"	: 15,
		"is_visible"	: true,
		"is_new"	: true,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"starter_crappy_ceiling"	: {
		"name"		: "Unfinished Ceiling",
		"category"	: "Concrete",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "starter_crappy_ceiling",
		"left"		: "starter_crappy_ceiling",
		"right"		: "starter_crappy_ceiling",
		"swatch"	: "starter_crappy_ceiling_swatch",
		"cost_credits"	: 0,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: true
	},
	"uralia_ceiling"		: {
		"name"		: "Uralia Sky Ceiling",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "uralia_ceiling",
		"main_2"	: "uralia_ceiling_2",
		"main_3"	: "uralia_ceiling_3",
		"main_4"	: "uralia_ceiling_4",
		"main_5"	: "uralia_ceiling_5",
		"main_6"	: "uralia_ceiling_6",
		"left"		: "uralia_ceiling",
		"right"		: "uralia_ceiling",
		"swatch"	: "uralia_ceiling_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: true,
		"is_default"	: false
	},
	"ioletoyageceiling"		: {
		"name"		: "Violet Voyage Sky",
		"category"	: "Novelty",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "violetvoyage_ceiling",
		"left"		: "violetvoyage_ceiling",
		"right"		: "violetvoyage_ceiling",
		"swatch"	: "violetvoyage_ceiling_swatch",
		"cost_credits"	: 40,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"white_crappy"			: {
		"name"		: "White Stucco Ceiling",
		"category"	: "Stucco",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "white_crappy_ceiling",
		"left"		: "white_crappy_ceiling",
		"right"		: "white_crappy_ceiling",
		"swatch"	: "white_crappy_ceiling_swatch",
		"cost_credits"	: 0,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"whitewood_ceiling"		: {
		"name"		: "White Wooden Ceiling",
		"category"	: "Wood",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "whitewood_ceiling",
		"main_2"	: "whitewood_ceiling_2",
		"main_3"	: "whitewood_ceiling_3",
		"main_4"	: "whitewood_ceiling_4",
		"left"		: "whitewood_ceiling",
		"right"		: "whitewood_ceiling",
		"swatch"	: "whitewood_ceiling_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"wood"				: {
		"name"		: "Wood Paneling",
		"category"	: "Wood",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "wood_ceiling",
		"left"		: "wood_ceiling",
		"right"		: "wood_ceiling",
		"swatch"	: "wood_ceiling_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	},
	"wood_cave"			: {
		"name"		: "Wooden Cave Ceiling",
		"category"	: "Wood",
		"swf"		: "home_wallpaper.swf",
		"sort_order"	: 0,
		"main"		: "wood_cave_ceiling",
		"left"		: "wood_cave_ceiling",
		"right"		: "wood_cave_ceiling",
		"swatch"	: "wood_cave_ceiling_swatch",
		"cost_credits"	: 25,
		"is_visible"	: true,
		"is_new"	: false,
		"is_subscriber"	: false,
		"is_default"	: false
	}
};

var homes_interior_frames = {
	"andra"		: {
		"double_frames"		: true,
		"floor_gap"		: 0,
		"frame_height"		: 53,
		"frame_hz_deco_top"	: "crosssection_top_horizontal_150px_andra1",
		"frame_hz_deco_btm"	: "crosssection_bottom_horizontal_150px_andra1",
		"frame_hz_w"		: 150,
		"frame_hz_h"		: 56,
		"frame_end_deco"	: "crosssection_endwall_andra1",
		"frame_end_w"		: 150,
		"frame_end_h"		: 564,
		"frame_open_deco"	: "crosssection_divider_end_andra1",
		"frame_open_w"		: 150,
		"frame_open_h"		: 281,
		"frame_open_y"		: 230,
		"frame_div_deco"	: "crosssection_divider_andra1",
		"frame_div_w"		: 150,
		"frame_div_h"		: 284,
		"frame_div_y"		: 227,
		"frame_div_center"	: false
	},
	"firebog"	: {
		"double_frames"		: false,
		"floor_gap"		: 20,
		"frame_height"		: 56,
		"frame_hz_deco_top"	: "crosssection_top_horizontal_500px_firebog1",
		"frame_hz_deco_btm"	: "crosssection_bottom_horizontal_500px_firebog1",
		"frame_hz_w"		: 500,
		"frame_end_deco"	: "crosssection_endwall_firebog1",
		"frame_end_w"		: 152,
		"frame_end_h"		: 570,
		"frame_open_deco"	: "crosssection_divider_end_firebog1",
		"frame_open_w"		: 164,
		"frame_open_h"		: 284,
		"frame_open_y"		: 230,
		"frame_div_deco"	: "crosssection_divider_firebog1",
		"frame_div_w"		: 164,
		"frame_div_h"		: 284,
		"frame_div_y"		: 230,
		"frame_div_center"	: true
	},
	"groddle"	: {
		"double_frames"		: false,
		"floor_gap"		: 0,
		"frame_height"		: 17,
		"frame_hz_deco"		: "crosssection_horizontal_1500px_groddle1",
		"frame_hz_w"		: 1500,
		"frame_end_deco"	: "crosssection_endwall_groddle1",
		"frame_end_w"		: 17,
		"frame_end_h"		: 492,
		"frame_open_deco"	: "crosssection_divider_end_groddle1",
		"frame_open_w"		: 17,
		"frame_open_h"		: 245,
		"frame_open_y"		: 230,
		"frame_div_deco"	: "crosssection_divider_groddle1",
		"frame_div_w"		: 17,
		"frame_div_h"		: 245,
		"frame_div_y"		: 231,
		"frame_div_center"	: true,
		"attic_left_deco"	: "attic_end_left",
		"attic_mid_deco"	: "attic_tile",
		"attic_right_deco"	: "attic_end_right",
		"attic_h"		: 208,
		"attic_h_visible"	: 65,
		"attic_platform"	: 35,
		"basement_left_deco"	: "crosssection_ground_end_left_groddle1",
		"basement_mid_deco"	: "crosssection_ground_tile_groddle1",
		"basement_right_deco"	: "crosssection_ground_end_right_groddle1",
		"basement_h"		: 58
	}
};


// generated ok
